### ISSUE TITLE
`test-linux-cmake` takes >60 minutes

### ISSUE THREAD

**Issue by mostafaelhoushi** [facebookresearch/CompilerGym#706]
## 🐛 Bug

Although `build-linux-cmake` is now taking <30 minutes, `test-linux-cmake` takes >60 minutes

## To Reproduce

1. Create a PR
2. Watch the CI

We can take a look at the build log here: https://github.com/facebookresearch/CompilerGym/runs/6864888281?check_suite_focus=true

## Expected behavior

Looking at the other tests and examples CI jobs of other platforms, it shouldn't take more than 20 minutes

## Environment

N/A

## Additional context

N/A

**Comment by ChrisCummins** [comment]
Thanks for uncovering this. If you look at the end of the build report, the slowest 5 tests are printed:

```
============================= slowest 5 durations ==============================
427.74s call     tests/loop_tool/actions_test.py::test_basic[cpu]
425.24s call     tests/llvm/datasets/cbench_validate_test.py::test_validate_benchmark_semantics[benchmark://cbench-v1/jpeg-d]
377.92s call     tests/llvm/datasets/cbench_validate_test.py::test_validate_benchmark_semantics[benchmark://cbench-v1/tiff2bw]
359.21s call     tests/llvm/datasets/cbench_validate_test.py::test_validate_benchmark_semantics[benchmark://cbench-v1/tiff2rgba]
350.26s call     tests/llvm/datasets/cbench_validate_test.py::test_validate_benchmark_semantics[benchmark://cbench-v1/dijkstra]
==== 1461 passed, 824 skipped, 1 xfailed, 12 xpassed in 3629.28s (1:00:29) =====
```

I'm not sure why the loop_tool test should be taking so long (@bwasti?).

For the validation tests, the problem is it's compiling each benchmark and running it 20+ times (using different datasets and different combinations of asan/tsan/msan etc). I have some ideas on how we could speed this up (basically run fewer datasets on $CI), will try them out.

BTW, there are a couple of flags that are useful for working on this. The first is the `--durations=<n>` flag which controls how many of the *n* slowest tests get printed at the end of testing (the default is 5, as seen above). There is also the `TEST_TARGET` var which can be used to force pytest to run on only one file / directory. The `CI` var is also set by github's action runners, and I use this var to run "faster" CI tests. Putting it together, here is how I'm debugging the validation tests:

```
$ time make install-test CI=1 PYTEST_ARGS='--durations=25' TEST_TARGET=tests/llvm/datasets/cbench_validate_test.py
```

Will submit a PR with my findings.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
As of v0.2.5 the `test-linux-cmake` job takes 27min. Most of this time is spent in the `loop_tool` tests, but I don't think we can avoid that. Closing.
