### ISSUE TITLE
Make all strings accessible from objects.

### ISSUE THREAD

**Issue by hughleat** [facebookresearch/CompilerGym#72]
## 🚀 Feature

String use is error prone and has little support from IDEs.
Instead of writing:
`    env.observation_space = "IRInstructionCountOs"`
which has an error that an IDE can't help me with because that space does not exist,
Write:
`    env.observation_space = compiler_gym.llvm.observation_spaces.IrInstructionCountOz`
Or something like that.
This way the IDE or debugger will auto complete for me and may even tell me there is an error before running it.

`compiler_gym.llvm.observation_spaces.IrInstructionCountOz` can still be a string, so minimal changes are required.

## Motivation

I don't like remembering things or continually having to look things up when the computer can do it for me.

The classes for this could be auto generated from the c++?

## Pitch

See above

## Alternatives

Don't do it?

## Additional context

None

**Comment by ChrisCummins** [comment]
This will be a definite quality-of-life improvement.

The script [compiler_gym.bin.service](https://facebookresearch.github.io/CompilerGym/cli.html#module-compiler_gym.bin.service) produces a human-readable description of the support observations/actions for a service. I'd suggest adding something like a `--output_format=py` flag that would spit out enum consts instead of markdown tables and hook that into the bazel build

Cheers,
Chris
