### ISSUE TITLE
Issue with `runtime_observation_count`

### ISSUE THREAD

**Issue by lqwk** [facebookresearch/CompilerGym#756]
## ❓ Questions and Help

As mentioned in our previous communications, I tried adding debugging logs into the code to print out the `runtime_observation_count` and corresponding callstacks to debug why we are seeing only 1 observation for starting runtimes.

See the debug logs in this [branch](https://github.com/lqwk/CompilerGym/tree/debug).

## Repro

The command I tested this with is:

```
python -m llvm_autotuning.tune -m \
    experiment=my-exp \
    outputs=/tmp/logs \
    executor.cpus=32 \
    num_replicas=1 \
    autotuner=nevergrad \
    autotuner.optimization_target=runtimeseries \
    autotuner.search_time_seconds=120 \
    benchmarks=single_benchmark_for_testing
```

and I got the following [logs](https://github.com/lqwk/CompilerGym/blob/debug/log7.txt)

## Details

- I verified that the `runtime_observation_count` is setup properly when we create the optimization target: [debug logs](https://github.com/lqwk/CompilerGym/blob/debug/log7.txt#L57)

- I saw that the `previous_runtimes` had a correct number of observations of 30 but during reset, the observation count was 1: [debug logs](https://github.com/lqwk/CompilerGym/blob/debug/log7.txt#L93-L100) and I couldn't figure out why.

- I also saw that there was a time when the `runtime_observation_count` was set to 1: [debug logs](https://github.com/lqwk/CompilerGym/blob/debug/log7.txt#L190-L191). The logs of the corresponding callstack is also printed [here](https://github.com/lqwk/CompilerGym/blob/debug/log7.txt#L170-L188).

**Comment by ChrisCummins** [comment]
Hey, I'm going to need your help debugging this, as logs and stacktraceds aren't useful to me without knowing the details of your code, and the repro command requires changes that aren't in upstream CompilerGym.

Could you please reduce your repro example to a standalone snippet of code that runs against an unmodified CompilerGym package and demonstrates the issue? Then I can run it on my end and see what the underlying problem is.

Cheers,
Chris
