### ISSUE TITLE
compiler arm  version

### ISSUE THREAD

**Issue by libin049** [facebookresearch/CompilerGym#798]
## ❓ Questions and Help
How to port compilergym to arm architecture？any plan?
## Additional Context
I am porting CompilerGym to ARM architecture, and the earlier steps were fine, but I encountered an issue during the final step：`pip install cmake_build/py_pkg/dist/compiler_gym*.whl --force-reinstall. `
```shell
ERROR: Could not find a version that satisfies the requirement loop-tool-py==0.0.7 (from compiler-gym) (from versions: 0.0.3, 0.0.4, 0.0.5)
ERROR: No matching distribution found for loop-tool-py==0.0.7
```

**Comment by ChrisCummins** [comment]
Hey libin049! The build error that you are seeing is because of the dependency `loop-tool`, which does not have an ARM-compatible binary. Provided you're not going to use the loop_tool environment, you could try simply removing the requirement here https://github.com/facebookresearch/CompilerGym/blob/development/compiler_gym/requirements.txt#L9 and seeing if that does the trick.

Hope that helps!

Cheers,
Chris

**Comment by libin049** [comment]
I make loop-tool version 0.0.5. It works.
