### ISSUE TITLE
Version conflict with python built-ins and MLIR

### ISSUE THREAD

**Issue by anthony0727** [facebookresearch/CompilerGym#831]
## ❓ Questions and Help

I think currently, with updated python versions, below should be explicitly installed.

```
pip install setuptools==65.5.0
pip install "wheel<0.40.0" 
```

**Comment by ChrisCummins** [comment]
Thanks!

**Comment by anthony0727** [comment]
@ChrisCummins Thanks for the reply and I have one more question!

Recently, I've been interested in GPU targeted program optimization. Especially at the level of MLIR, triton lang.

Do you think is it possible to integrate triton's IR into compiler-gym's MLIR env?

OR

To implement an MLIR env or dataset on my own, could you give me an advice where to start..? seems like I have to understand the process of implementing a `Dialect`..?

AFAIK, triton's IR is implemented upon MLIR.
https://github.com/triton-lang/triton/blob/main/include/triton/Dialect/Triton/IR/Interfaces.h
https://github.com/triton-lang/triton/blob/main/lib/Dialect/TritonGPU/IR/Dialect.cpp

**Comment by ChrisCummins** [comment]
> Do you think is it possible to integrate triton's IR into compiler-gym's MLIR env?

As I recall the MLIR environment is tailored to support only one particular case of matrix multiplication and isn't very generalizable. I'm not sure if integrating your use case into the existing environment would make sense.

On the other hand, the existing MLIR env may make for a good start for defining your own environment, since much of the boilerplate about compiling the right version of LLVM and setting up the skeleton code for exposing a CompilerGym environment from C++ will be handled for you. So perhaps just fork the existing MLIR environment and hack on that, then we could always look into integrating+merging your changes upstream later?

Cheers,
Chris

**Comment by anthony0727** [comment]
Yup! I'm on simple PoC project, thanks for the advice!
